services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./local.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - existdb
      - fuseki
    networks:
      - backend

  fuseki:
    image: secoresearch/fuseki:latest
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    networks:
      - backend

  existdb:
    build:
      context: .
      args:
        EXIST_VERSION: release
        BUILD: local
    container_name: exist
    ports:
      - "8080:8080"
    environment:
      - EXISTDB_ADMIN_PASSWORD=admin
    networks:
      - backend

networks:
  backend:
    driver: bridge