# This workflow builds a xar archive, deploys it into exist and execute a simple smoke test.
# It also includes code for using semantic-release to upload packages as part of GitHub releases
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# For node free automated release see https://trstringer.com/github-actions-create-release-upload-artifacts/

name: exist-db CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
        # 7.0.0-SNAPSHOT and 6.2.1 created
         exist-version: [latest, release]
         java-version: [11, 21]
         exclude:
           - exist-version: release
             java-version: 21
           - exist-version: latest
             java-version: 11

    steps:
      # Checkout code
      - uses: actions/checkout@v4
      - name: Install Test Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils bats
      # sanity check
      # TODO(DP) Validate ?
      - name: Ensure all XML files are well-formed
        run: |
          xmllint --noout \
            $(find . -type f -name '*.xml')

      # Build
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
        
      - name: Build Expath Package
        working-directory: ./gez-en-2.6
        run: ant

      - name: Add Expath Dependency
        working-directory: ./gez-en-2.6/build/
        run: wget https://github.com/eXist-db/shared-resources/releases/download/v0.9.1/shared-resources-0.9.1.xar -O 001.xar

      # Install
      - name: Start exist-ci containers
        run: |
          docker cp ./gez-en-2.6/build/*.xar /exist/autodeploy
          docker run -dit -p 8080:8080  \
          --name exist --rm --health-interval=2s --health-start-period=4s \
          duncdrum/existdb:${{ matrix.exist-version }}
          sleep 15s

      # Test
      - name: Run test
        run: bats --tap test/*.bats

      # Lint commit messages
      # - name: lint commit message
      #   uses: wagoid/commitlint-github-action@v6
  
